### ISSUE TITLE
Translate Package Document to Chinese

### ISSUE THREAD

**Issue by Piaoshi** [AlphaZTX/fixdif#3]
我准备翻译一下宏包文档。
有人在翻译了吗？
有什么建议吗？

**Comment by AlphaZTX** [comment]
我今天中午更新1.3版，直接翻译1.3版的吧，感谢你的付出！目前应该是没有人翻译这个手册。考虑到国内绝大多数用户没有看手册的习惯，我就没写中文版的手册，如果后续这个需求（指中文版手册）很强烈，我也会将中文版手册加进来。-------- 原始邮件 --------发件人： Piaoshi ***@***.***>日期： 2022年6月7日周二 01:03收件人： AlphaZTX/fixdif ***@***.***>抄送： Subscribed ***@***.***>主    题： [AlphaZTX/fixdif] Translate Package Document to Chinese (Issue #3)

我准备翻译一下宏包文档。

有人在翻译了吗？

有什么建议吗？

**Comment by AlphaZTX** [comment]
可以翻译一份，提交到 alphaztx@163.com 即可。目前的版本是 1.3a。
1.x 的版本号下的文档不会有重大更新，第 6 节暂时不需要翻译。

非常感谢你的热情！

**Comment by AlphaZTX** [comment]
我自己重新写了一个中文文档，发到 repo 里面了
