### ISSUE TITLE
Problems with `unicode-math`

### ISSUE THREAD

**Issue by syvshc** [AlphaZTX/fixdif#5]
here is the code:

```latex
\documentclass{article}
\usepackage{fixdif}
\usepackage{unicode-math}
\setmathfont{TeX Gyre Pagella Math}
\setmathfont{XITS Math}[range = \setminus]
\begin{document}
  $ A \setminus B $ 
\end{document}
```

![image](https://user-images.githubusercontent.com/38098591/226271222-5b66c697-3d5c-4783-a7f8-26ab89af3a4a.png)

It gives a warning no matter of the order of `unicode-math` and `fixdif`, saying 

```
Missing character: There is no ⧵ (U+29F5) in font TeXGyrePagellaMath-Regular/OT
:script=math;language=dflt;!
```
If I unuse `fixdif`, it works well.

**Comment by AlphaZTX** [comment]
Fixed in #6 .
