### ISSUE TITLE
[Suggestion] 对转置、trace、rank 等的支持

### ISSUE THREAD

**Issue by myhsia** [AlphaZTX/fixdif#8]
- 希望在这个包中包含进矩阵转置那个 T 的 command（比如＼T）的正确定义（详见好久前知乎上的文章https://zhuanlan.zhihu.com/p/27490955?utm_id=0，@刘海洋 给出了好几种写法，后来也说 mathsf 的算是“正规”些）
- 矩阵的迹 Tr，秩rank 的正体也最好定义进去，1是方便，2是很多用户在导言区都把＼Tr 定义成了 mathrm 那种，而非Declare 一个 Mathoperator（当然，由于涉及矩阵，maybe 这个放到physics2里更好？（笑））
- 顺带一提，还有复变函数里的 Im，Re，一般都是正体但是默认是一种花体字，可以在 fixdif 包加个option，启动这个 option 就 renewcommand 成 mathoperator 那样正体的；同时还有虚数 i，自然对数底数 e，建议都像 fixdif 那样定义个命令＼i，＼e～
Thanks.

**Comment by AlphaZTX** [comment]
@xiamyphys 你这个 issue 看得我血压上来了……我想到啥说啥，接下来说的话会很直。

这些问题跟 fixdif 无关，fixdif 写出来就是为了解决微分算符前后间距这么一个问题的。你说的这些需求，要加也是加到 physics2 里。但是，真的有必要加吗？

先看你的第一个需求。再看一次本包的简介：

> The fixdif package provides an interface for defining the style of differential operators.

所以，不加。

多说一句，矩阵转置的记号无论怎么写，都是可接受的。无论是ISO还是国标，抑或是英国在这方面的标准，都不是强制的（与此相关的国标曾经是中国大陆出版物的强制标准，后大多数改为推荐性标准）。即使是在被推荐用无衬线上标T表示转置的英国人写的书里，你也能看见满天飞的 ^T 用来表示转置。另外，看东西要看全，你看你放的链接最后，作者还是推荐用衬线的上标 T 表示转置，我也习惯这么写。但无论你怎么写，你最好先说明一下你的记号表示啥意思，否则读者骂娘甚至给你寄刀片都是有可能的。这种简单的问题无需纠结，嫌麻烦的话，自己在导言区随手写一行定义一下，在文章中说明一下就完事了。

排版是灵活的，要允许差异的存在。比如 unicode-math 就支持 TeX，ISO 等不同的风格。每一种风格都对应着一类形成已久的习惯，不能说不同于 ISO 或者不同于国标的就要一棒子打死。玩排版不能玩着玩着给自己玩成不知变通的傻子。

然后看你的第二个需求。你猜 physics2 里面有没有实现过？如果你建议作者加一些新的 feature 到某个库，那你最好是先读完现版本的文档，再想要不要提出这个建议。就在你提这个 issue 时，physics2 的版本号是 1.0.1，physics2.pdf 的第 13 页 3.4 小节介绍了 op.legacy module，看一遍，你的需求就解决完了。

最后看你的第三个需求。首先，这个需求跟 fixdif 要解决的问题有关吗？无关，所以不会加进去。再看 physics2.pdf v1.0.1 Sec 3.4，你的需求又一次解决完了。甚至，你的第二个和第三个需求在 physics2 大版本号是 0 的时候就被解决过了。

三个需求给你解决了俩，不用谢。

**Comment by AlphaZTX** [comment]
@xiamyphys 下次发 issue 前先检查一遍，不要出现错别字，注意插入链接的格式。汉字和英文、阿拉伯数字之间要么都加空格，要么都不加空格。虽然你提 issue 的态度很好，但不得不说这个 issue 的质量较差。
