### ISSUE TITLE
Wrong spacing when following negative sign

### ISSUE THREAD

**Issue by UlyssesZh** [AlphaZTX/fixdif#9]
```tex
\documentclass{article}
\usepackage{fixdif}
\begin{document}
\[{-\d}\quad{-\partial}\]
\end{document}
```

Expected:
![image](https://github.com/user-attachments/assets/3a9a4777-d50c-4a46-96d1-7259ad4727c0)

Actual:
![image](https://github.com/user-attachments/assets/c3d3053d-40c2-488c-9c2c-413a65507ad9)

**Comment by AlphaZTX** [comment]
见 `fixdif-zh-cn.pdf` 最后一段或 `fixdif.pdf` Page 6。正常现象。

Use
```
\[ -{\d foo} \neq -{\partial baz}. \]
```
instead.

**Comment by UlyssesZh** [comment]
技术原因还是设计如此?
